# -*- coding: utf-8 -*-
"""정보 기말 코드 실행 결과.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v14S6M2bDvpVhqh60X6bKPqX9E5ecWGf
"""

#6

print(list(range(-5,5,2)))
print([i for i in range(-5,5,2)])
print(list((reversed(range(3,-6,-2)))))
print([2*i + 1 for i in range(-3,3)])
print([i for i in range(-6,5) if i % 2 == 1])

#정답 4번

#7

arr = [6,1,2,3,8]
n = len(arr)

for i in range(n-1):
  for j in range(n - 1 - i):
    if arr[j] < arr[j+1]:
      arr[j], arr[j+1] = arr[j+1], arr[j]

print(arr)

#정답 2번

#9

A = [1,2,3,4,5]
result = [A.pop(0)*i for i in A if i % 2 == 0]
print(result)

#정답 3번

#10

x = 3
y = 5

def fun1():
  x = 10
  def fun2():
    global y
    print(x+1)
    y += 2
  fun2()
  print(x)
  print(y+1)

fun1()
print(x)
print(y)

#정답 : 1번

#11

count = 0
def explore(n):
  global count
  count += 1
  if n == 0:
    return
  explore(n-1)
  explore(n-1)

explore(3)
print(str(count) + "회")

#정답 : 4번

#12

#모든 코드는 원래 각 숫자가 서로 다른 줄에 출력되지만 가독성을 위해 List 형태로 출력했음을 알려드립니다
#리스트.append(i)라고 작성된 모든 코드는 시험지에서 print(i)임을 감안하고 확인해주세요

#보기 1번
a1 = []
i = 1
while i <= 10:
  if i % 2 == 1:
    if i == 5:
      break
    a1.append(i)
  i += 1
print("보기 1번 :", *a1)

#보기 2번 - 출력 하다가 중간에 멈춥니다
a2 = []
i = 1
while i <= 10:
  if i % 2 == 1:
    if i == 5:
      i += 1 #이 코드는 시험지에 없으나 i += 1을 사용하지 않으면 출력이 멈추는 문제가 생겨서 작성합니다
      continue
    a2.append(i)
  i += 1
print("보기 2번 :", *a2)

#보기 3번
a3 = []
i = 1
while i <= 10:
  if i == 5:
      i += 1
      continue
  if i % 2 == 1:
      a3.append(i)
  i += 1
print("보기 3번 :", *a3)

#보기 4번
a4 = []
i = 1
while i <= 10:
  if i % 2 == 1:
      a4.append(i)
  if i == 5:
    i += 1 #이 코드는 시험지에 없으나 i += 1을 사용하지 않으면 출력이 멈추는 문제가 생겨서 작성합니다
    continue
  i += 1
print("보기 4번 :", *a4)

#보기 5번
a5 = []
i = 1
while i <= 10:
  if i == 5:
      break
  if i % 2 == 1:
      a5.append(i)
  i += 1
print("보기 5번 :", *a5)


#정답 : 3번

#13

import random as R

nums = R.randint(1,10)
print(nums)

#정답 : 2번

#14

text = 'hello python world'
letters = set()

for ch in text:
  if ch != ' ':
    letters.add(ch)

print(len(letters))

#정답 : 4번

#서술형 3

A = [1,2,3,4]
B = [3,4,5,6]

intersection = [a for a in A if a in B]   #ㄱ
difference = [a for a in A if a not in B] #ㄴ

print("교집합 : ", intersection)
print("차집합 (A-B) :", difference)

#서술형 4

N, S = map(int, input().split())
keys = list(map(int,input().split()))
keys.sort() #ㄱ

for i in range(0,N,S):
  print(*keys[i:i+S]) #ㄴ

#서술형 5

fruits = {}
N = int(input())

for i in range(N):
  name,price = input().split()
  fruits[name] = int(price)

max_price = max(fruits.values()) #ㄱ
min_price = min(fruits.values()) #ㄴ

expensive = [name for name,price in fruits.items() if price == max_price] #ㄷ

print(f"가장 비싼 가격 :  {max_price}")
print(f"가장 저렴한 가격 : {min_price}")
print("가장 비싼 과일: ", ', '.join(expensive))

#서술형 6

def show_items(*items,title = "식사"): #ㄱ
  print(title)
  for i in items :
    print(i, end = ' ')
  print()

show_items("한식","중식","양식")
show_items("과일", "떡", "쿠키", title = "간식")  #ㄴ

#서술형 7

#원본 코드 - 이진수가 반대로 출력되는 문제
def to_binary(n):
  result = ''
  while n > 0:
    result += str(n % 2)
    n = n//2
  return result
A = int(input())
print(to_binary(A))

#수정안 1
def to_binary(n):
  result = ''
  while n > 0:
    result = str(n % 2) + result
    n = n//2
  return result
A = int(input())
print(to_binary(A))

#수정안 2는 아직 구현 못함

#서술형 8

def sum_recursive(n):
  #ㄱ
  if n == 0:
    return 0
  return n + sum_recursive(n-1)

N = int(input())
sum_recursive(N)

#서술형 9

A = set(["KOR","ENG","MATH", 'INFO'])
B = set(['INFO','SCI','SOC','ENG'])

for subject in A&B :
  A.discard(subject)
  B.remove(subject)

W = set(["SCI",'ART','KOR'])

A.update(W | A)
B.update(W ^ B)

print("A:", *sorted(A))
print("B:", *sorted(B))

#서술형 10

def hanoi(n,start,target,temp):
  if n == 1:
    print(f"원판 1을 {start}에서 {target}으로 이동")
    return
  hanoi(n-1,start,temp,target) #ㄱ
  print(f'원판 {n}을 {start}에서 {target}으로 이동')
  hanoi(n-1, temp, target, start) #ㄴ

n = int(input("원판 개수:"))
hanoi(n,'A','C','B')

print("다들 정보 기말고사 보느라 수고하셨습니다!")
print("남은 시험기간도 화이팅 하시고 좋은 결과 있길 바랍니다.")